### ISSUE TITLE
[Bug] Wrong path separator in Windows

### ISSUE THREAD

**Issue by pidgeon777** [oflisback/obsidian-bridge.nvim#12]
This line:

https://github.com/oflisback/obsidian-bridge.nvim/blob/01c83f34907f1654725120398dc66c246e13ed4f/lua/obsidian-bridge/init.lua#L38

Should be changed to something as follows:

```lua
local path_sep = (vim.fn.has("win32") == 1) and "\\" or "/"

return string.match(filename_incl_path, ".+".. path_sep .. "(.+)$")
```

By doing so, the plugin will work on Windows as well.

**Comment by oflisback** [comment]
Thank you that seems likely to be correct. Do you have access to a windows environment? Would you mind making a PR and check that it works on windows, then I can verify on my side and we can integrate it.

**Comment by oflisback** [comment]
Hopefully this was fixed with https://github.com/oflisback/obsidian-bridge.nvim/pull/13 🤞

**Comment by oonamo** [comment]
Finally got a chance to test it out for a longer period of time and it's working. I also used the scroll sync patch, and its working well!
