### ISSUE TITLE
BUG: Opening wrong file with the same name

### ISSUE THREAD

**Issue by carlossgv** [oflisback/obsidian-bridge.nvim#16]
I have something like this:

`vault_folder/inbox.md` and `vault_folder/another_folder/inbox.md`

When I open nvim buffer of `another_folder/inbox.md`, it opens `vault_folder/inbox.md` in Obsidian.

If the file has any other name in any folder it works just fine.

**Comment by oflisback** [comment]
Fixed with https://github.com/oflisback/obsidian-bridge.nvim/pull/17 thanks @carlossgv!
