### ISSUE TITLE
add commands to toggle the plugin on and off

### ISSUE THREAD

**Issue by iAurora** [oflisback/obsidian-bridge.nvim#19]
Hi! Your plugin is exactly what I needed but didn't expect to find in existence. Thank you!

A lot of the notes I take do not require a previewer though, and I do not have Obsidian running all the time. Suggested Lazy configuration loads Obsidian Bridge for all markdown files regardless, and curl error gets displayed every time I switch to a different buffer.

Lazy loading the plugin on `keys` or `cmd` helps somewhat, but you need to switch buffers for things to start working and quitting Neovim is the only way to deactivate.

It would help to have `ObsidianBridgeOn`, `ObsidianBridgeOff` and `ObsidianBridgeToggle` commands in the way [MarkdownPreview](https://github.com/iamcco/markdown-preview.nvim) offers them for example.

**Comment by oflisback** [comment]
Hi @iAurora and thanks for the suggestion!

I've made the change, please try it out and let me know if it works for you.

**Comment by iAurora** [comment]
All 3 commands seem to work, thank you! Having the ability to toggle the plugin on and off makes working with it much more pleasant.

The commands are perfectly usable as they are, but if you ever feel like improving the experience a bit further things to consider could be:

1. Make `ObsidianBridgeOn` (and ideally `ObsidianBridgeToggle` if the state is not currently `on`) send a `post` request for a currently open buffer. Right now if you want to preview the current buffer in Obsidian, you need to invoke the command, switch to a different buffer and then go back to a current one.

2. Display some kind of message for plugin being activated. As (1) is not happening, when you invoke `ObsidianBridgeOn` or `ObsidianBridgeToggle` using a keymap, there is no feedback at all.

3. As running Obsidian Bridge doesn't make sense without Obsidian and attempting to results in an error, it would be nice if activating the plugin launched Obsidian automatically.

**Comment by oflisback** [comment]
This is turning out great, thanks a lot! I implemented (1) and (2) but I'm a little less sure how to deal with (3) and details around that, if you're up to for I'd be happy to review a PR. :nerd_face:

**Comment by iAurora** [comment]
Thanks! `ObsidianBridgeOn` and `ObsidianBridgeOff` work perfectly now and getting visual feedback feels really nice.

There seems to be a little problem with `ObsidianBridgeToggle`.  If I restart Neovim and use the command to activate Obsidian Bridge for the first time, it gives me a `obsidian-bridge deactivated` message instead. Sending the command the second time activates the plugin as expected and it works fine past that.

(3) seems fairly trivial to achieve for macOS as `open obsidian://` in the shell brings the app to the front and launches it if it's not already running. I don't have the means to test it on the other systems and provide a complete solution, unfortunately.  I wouldn't worry too much about it anyway as it's just a nicety and would probably need to be optional to avoid complications in situations where it does not work.

**Comment by oflisback** [comment]
> There seems to be a little problem with `ObsidianBridgeToggle`. If I restart Neovim and use the command to activate Obsidian Bridge for the first time, it gives me a `obsidian-bridge deactivated` message instead. Sending the command the second time activates the plugin as expected and it works fine past that.

That's because the plugin is activated by default. Unless the state is persisted between restarts that's the default that is backwards compatible and hopefully default on makes most sense.

**Comment by iAurora** [comment]
> > There seems to be a little problem with `ObsidianBridgeToggle`. If I restart Neovim and use the command to activate Obsidian Bridge for the first time, it gives me a `obsidian-bridge deactivated` message instead. Sending the command the second time activates the plugin as expected and it works fine past that.
> 
> That's because the plugin is activated by default. Unless the state is persisted between restarts that's the default that is backwards compatible and hopefully default on makes most sense.

The problem is, that's still the behavior when the plugin is not active. You seem to be assuming its state rather than checking for it.

I don't need to have all of my .md notes previewed in Obsidian all the time. A lot of them are just lightly formatted text that is perfectly readable in Neovim. I even have images displayed there. So it doesn't make sense to automatically load and activate Obsidian Bridge each time I want to edit an .md note. And so I don't have this part in my Lazy config:

```lua
event = {
  "BufReadPre *.md",
  "BufNewFile *.md",
  },
```

which would do exactly that. Instead I have 

```lua
keys = {
  {
    "<leader>bb",
    "<cmd>ObsidianBridgeToggle<cr>",
    desc = "Toggle Obsidian Bridge",
  },
},
cmd = {
  "ObsidianBridgeOn",
  "ObsidianBridgeToggle",
  },
```

which loads and activates the plugin only when I invoke it with a shortcut or a command.

So when I open a new instance of Neovim and an .md file in it, the default state is actually `off` and `ObsidianBridgeToggle`'s behavior seems buggy.
