### ISSUE TITLE
What is the correct URL to install the Rest API fork with scroll?

### ISSUE THREAD

**Issue by YousufSSyed** [oflisback/obsidian-bridge.nvim#21]
https://github.com/oflisback/obsidian-bridge.nvim?tab=readme-ov-file
> Add https://github.com/oflisback/obsidian-local-rest-api with release version tag v1.0.0. The added plugin is called "Local REST API with scroll".

When I paste the URL into BRAT, I get a notification saying 
> oflisback/obsidian-local-rest-api
> The release is not complete and cannot be download. main.js is missing from the Release

**Comment by oflisback** [comment]
I can't reproduce this myself, I'm on MacOS using latest Obsidian version 1.6.7 and latest BRAT version 1.0.3.

Let me know if you can provide some more info on how this happens and verify that in BRAT you select "Add Beta plugin with frozen version" and then:

Repository: https://github.com/oflisback/obsidian-local-rest-api

Version: v1.0.0

**Comment by YousufSSyed** [comment]
I missed the part saying In the settings for BRAT, select "Add beta plugin with frozen version".
