### ISSUE TITLE
Bug: Percent encoded strings not properly received by Obsidian

### ISSUE THREAD

**Issue by ficcdaf** [oflisback/obsidian-bridge.nvim#25]
When opening a file in Neovim that has a space in the title, it seems the percent encoded string is not being received by Obsidian properly, or this plugin is not sending it in the right format. For example:

![image](https://github.com/user-attachments/assets/bafcce0c-675c-442a-a9ef-9752346a8f66)

As you can see, when I try to access the "Annotated Bibliography.md" file, Obsidian instead seems to receive a request for "Annotated%20Bibliography.md", sees there is no such file, and creates a new one. 

I believe this may be related to Issue #24. I will investigate and attempt to implement a fix, but help would be appreciated.

**Comment by ficcdaf** [comment]
It seems like the Obsidian Local REST API plugin released a new version with some breaking API changes which I suspect could be the culprit.

**Comment by oflisback** [comment]
Thanks for reporting the bug and thanks for investigating, if you have a chance, please see if https://github.com/coddingtonbear/obsidian-local-rest-api/releases/tag/3.0.3 fixes the problem for you, it seems likely based on your description.
