### ISSUE TITLE
Is the "Sync of buffer scrolling" fork of Obsidian-Rest-API stable?

### ISSUE THREAD

**Issue by ficcdaf** [oflisback/obsidian-bridge.nvim#26]
What it says on the tin. I'm having a great time with this plugin, the last missing piece for me would be the scrolling sync. I see that it required a forked version of the Obsidian REST API plugin. Considering I was having some issues earlier with the main Rest plugin that were fixed with an update, I'm just curious to know whether the forked version is up-to-date with the main release, or whether it's stable enough to be used in its current state. 

I'd basically just like to know whether anyone is currently using it, and how it's working with the latest version of obsidian-bridge and the Obsidian app; before I spend a lot of time setting it up just for the forked itself to be too outdated to use. 

Thanks!

**Comment by oflisback** [comment]
The BRAT approach described in the README is the easiest to do I think and it works well, give it a spin and let me know how it goes :rocket:
