### ISSUE TITLE
Opens all markdown files in obsidian

### ISSUE THREAD

**Issue by sidequestboy** [oflisback/obsidian-bridge.nvim#4]
When I edit a markdown file outside of my vault, it opens in obsidian also.

I would expect only vault markdown files to sync.

**Comment by sidequestboy** [comment]
perhaps [here](https://github.com/oflisback/obsidian-bridge.nvim/blob/28c015a32ea10df0c4d4106a8334e14d83c2b779/lua/obsidian-bridge/init.lua#L9) you could narrow the files for this autocmd with the `pattern` option, alongside a vault directory configuration option.

**Comment by oflisback** [comment]
I agree, I really want to [fix that too](https://github.com/oflisback/obsidian-bridge.nvim#crystal_ball-future). I imagine the ideal way to do it is already done in a lot of projects where they need to determine if the buffer is inside a git repo or not by checking parent folders for a .git folder. In the same way we could look for an .obsidian folder to determine if we're in a vault.

**Comment by sidequestboy** [comment]
hmm, maybe you could look for the `.obsidian` folder that exists in a vault root in the file's parent paths in the autocmd then

**Comment by oflisback** [comment]
Thanks a lot for bringing it up and for the fix suggestion, I just pushed a fix with https://github.com/oflisback/obsidian-bridge.nvim/commit/d21462f18a5366913f4f16fa56c5ad66a65945f5.

**Comment by sidequestboy** [comment]
beautiful! it works for me thank you! 🚀
