### ISSUE TITLE
curl unhandled response

### ISSUE THREAD

**Issue by atpur-rafif** [oflisback/obsidian-bridge.nvim#8]
Thank you so much for creating this extension. At first, there is some bug when I open file with parentheses character in the filename. After figuring out what happened, the reason of it because url not encoded when sending request. Then I tried using `topic/use-plenary-curl-wrapper` branch. Obsidian now open requested file, but nvim showing this error after opening a buffer:
```
Error executing vim.schedule lua callback: Vim:E474: Attempt to decode a blank string
stack traceback:
        [C]: in function 'json_decode'
        ...azy/obsidian-bridge.nvim/lua/obsidian-bridge/network.lua:14: in function <...azy
/obsidian-bridge.nvim/lua/obsidian-bridge/network.lua:13>
```
I think the problem because the [open file api](https://coddingtonbear.github.io/obsidian-local-rest-api/#/Open) have empty response. Is it possible to fix it by adding more handler? and will plenary curl wrapper branch be merged with main?

**Comment by oflisback** [comment]
Hi @atpur-rafif, thanks a lot for your report and for reminding me about the `topic/use-plenary-curl-wrapper` which could now be merged. I also saw the same problem as you resulting in "Attempt to decode a blank string" and have fixed it, please try it out. :crossed_fingers:

**Comment by atpur-rafif** [comment]
I've tried the update, it works perfectly. Even curl blocking bug, when it trying to contact the server, but the server still down (or obsidian still closed), fixed with `plenary.async`. Thanks for the update!
