### ISSUE TITLE
Integrate this with Obsidian.nvim for discoverability

### ISSUE THREAD

**Issue by Feel-ix-343** [oflisback/obsidian-bridge.nvim#9]
I am astounded that this plugin exists, as it is exactly what I have been looking for! 

That being said, I would have discovered this if it was in Obsidian.nvim.

Could you make a PR to add these features and commends to Obsidian.nvim??

**Comment by oflisback** [comment]
Thank you it's great to hear that you find it useful. Maybe you could suggest they put a link in their README, not sure it belongs in [obsidian.nvim](https://github.com/epwalsh/obsidian.nvim).
